- name: install nginx
  pacman: name=nginx state=present
  when: ansible_os_family == 'Archlinux'
- name: deploy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: nginx start
  systemd:
    name: nginx
    state: started
    enabled: True
