- name: install nginx
  pacman: name=nginx state=present
  when: ansible_os_family == 'Archlinux'
- name: render nginx.conf
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
- name: nginx start
  systemd:
    name: nginx
    state: started
    enabled: True
