- hosts: all
  user: ansible
  become: yes
  roles:
    - git
    - go
    - nginx
    - mariadb
    - postfix
    - vim
    - zsh
    - dovecot
    - iptables
    - monit
    - mackerel
    - php
  tasks:
    - name: install all
      pacman: name={{ item }} state=installed
      when: ansible_os_family == 'Archlinux'
      with_items:
        - bash-completion
        - zsh-completions
        - tig
        - wget
        - htop
        - rsync
        - tmux
        - nmap
