# ansible-playbook mariadbinit.yml
- hosts: dbserver
  user: ansible
  become: yes
  vars:
    password: "password"
  tasks:
    - name: install mariadb
      pacman: name=mariadb state=present
      when: ansible_os_family == 'Archlinux'
    - name: install python-pexpect
      pacman: name=python-pexpect state=present
      when: ansible_os_family == 'Archlinux'
    - name: install python2-pexpect
      pacman: name=python2-pexpect state=present
      when: ansible_os_family == 'Archlinux'
    - name: mariadb init
      become: yes
      command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
    - name: mariadb start
      systemd: state=started name=mariadb
    - name: /usr/bin/mysql_secure_installation
      expect:
        command: /usr/bin/mysql_secure_installation
        responses:
          "Enter current password for root \\(enter for none\\): " : ""
          "Set root password\\? \\[Y\\/n\\] " : "Y"
          "New password: " : "{{ password }}"
          "Re-enter new password: " : "{{ password }}"
          "Remove anonymous users\\?" : "y"
          "Disallow root login remotely\\?" : "y"
          "Remove test database and access to it\\?" : "y"
          "Reload privilege tables now\\?" : "y"
    - name: mariadb restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: mariadb
    - name: mariadb enable
      systemd:
        name: mariadb
        state: started
        enabled: True
