- name: install postfix
  pacman: name=postfix state=present
  when: ansible_os_family == 'Archlinux'
- name: render main.cf
  template:
    src=templates/main.cf.j2
    dest=/etc/postfix/main.cf
- name: render vmailbox
  template:
    src=templates/vmailbox.j2
    dest=/etc/postfix/vmailbox
- name: deploy master.cf
  copy:
    src: master.cf
    dest: /etc/postfix/master.cf
- name: create group vmail
  group: name=vmail gid=5000
- name: create users vmail
  user: name=vmail uid=5000 state=present groups=vmail shell=/usr/bin/nologin home=/home/vmail createhome=yes
- name: postmap vmailbox
  command: postmap /etc/postfix/vmailbox
  args:
    creates: /etc/postfix/vmailbox.db
- name: postmap virtual
  command: postmap /etc/postfix/virtual
  args:
    creates: /etc/postfix/virtual.db
- name: deploy /etc/aliases
  command: mv /etc/postfix/aliases /etc/aliases
  args:
    creates: /etc/aliases
- name: root mail
  lineinfile:
    dest: /etc/aliases
    line: "root: {{ mailroot }}"
- name: newaliases
  command: newaliases
  args:
    creates: /etc/aliases.db
