- name: deploy mackerel.service
  become: yes
  copy: src=mackerel.service dest=/usr/lib/systemd/system/mackerel.service owner=root group=root mode=644 backup=yes
- name: systemctl enable mackerel
  systemd:
    name: mackerel
    state: started
    enabled: True
- name: mackerel start
  service:
    name=mackerel state=started
