- name: Update all packages
  pacman: update_cache=yes upgrade=yes
  when: ansible_os_family == 'Archlinux'
- name: Old pacman cache delete
  command: /sbin/paccache -r
  when: ansible_os_family == 'Archlinux'
