- name: install zsh
  yum: name=zsh state=present
  when: ansible_os_family == 'RedHat'
- name: deploy zshrc at user
  become: yes
  become_user: "{{ username }}"
  copy:
    src: zshrc
    dest: ~/.zshrc
- name: deploy zshrc at root
  become: yes
  copy:
    src: zshrc
    dest: ~/.zshrc
- name: root default shell is /bin/zsh
  user: name=root shell=/bin/zsh
