- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
- name: install mariadb
  apt: name=mariadb-server state=present
  when: ansible_os_family == 'Debian'
- name: install mysql-python
  apt: name=python-mysqldb state=present
  when: ansible_os_family == 'Debian'
- name: deploy my.cnf
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf
- name: set rootpass
  mysql_user:
    login_user=root
    login_password={{ mariadbrootpassword }}
    login_port=3306
    host=localhost
    name=root
    password={{ mariadbrootpassword }}
    check_implicit_admin=yes
    state=present
    login_unix_socket=/run/mysqld/mysqld.sock
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: Removes the MySQL test database
  mysql_db: db=test state=absent
- name: create database
  mysql_user: name={{ dbname }} password={{ dbpassword }} priv=*.*:ALL state=present
