- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
- name: Add MariaDB.repo
  copy: src=MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo
  when: ansible_os_family == 'RedHat'
- name: install mariadb
  yum: name=MariaDB-server state=present
  when: ansible_os_family == 'RedHat'
- name: install mariadb
  yum: name=MariaDB-client state=present
  when: ansible_os_family == 'RedHat'
- name: install mysql-python
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'
- name: deploy my.cnf
  copy:
    src: centos.my.cnf
    dest: /etc/my.cnf
- name: make mariadb.service.d directory
  file:
    path=/etc/systemd/system/mariadb.service.d
    state=directory
    owner=root
    group=root
    mode=0755
- name: deploy mariadb.service.d/limits.conf
  become: yes
  copy: src=limits.conf dest=/etc/systemd/system/mariadb.service.d/limits.conf owner=root group=root mode=644 backup=yes
- name: mariadb start
  service:
    name=mariadb state=started
- name: set rootpass
  mysql_user:
    login_user=root
    login_password={{ mariadbrootpassword }}
    login_port=3306
    host=localhost
    name=root
    password={{ mariadbrootpassword }}
    check_implicit_admin=yes
    state=present
    login_unix_socket=/var/lib/mysql/mysql.sock
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: Removes the MySQL test database
  mysql_db: db=test state=absent
- name: create database
  mysql_user: name={{ dbname }} password={{ dbpassword }} priv=*.*:ALL state=present
- name: systemctl enable mariadb
  systemd:
    name: mariadb
    enabled: True
    daemon_reload: yes
