- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: install git
  yum: name=git state=present
  when: ansible_os_family == 'RedHat'
