set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac
set clipboard=unnamedplus
set number
set title
set hidden
set showmatch
set noexpandtab
set tabstop=4
set shiftwidth=4
set smartindent
set ignorecase
set smartcase
set nowrapscan
set hlsearch
set wrap
set incsearch
set ruler
set showcmd
set hidden
set history=2000
set paste
set sh=zsh
set cursorline
set laststatus=2
set statusline=%F%m%=[%p%%]\ (%l,%c)\ %{fugitive#statusline()}\ %{'['.(&fenc!=''?&fenc:&enc).']\ ['.&fileformat.']'}
set nocompatible
filetype plugin indent on
syntax enable
syntax on
highlight StatusLine term=none cterm=none ctermfg=white ctermbg=black
