- name: install others
  pacman: name={{ item }} state=installed
  when: ansible_os_family == 'Archlinux'
  with_items:
    - bash-completion
    - zsh-completions
    - tig
    - wget
    - htop
    - rsync
    - tmux
    - nmap
    - openbsd-netcat
