- name: install others
  apt: name={{ item }} state=installed
  when: ansible_os_family == 'Debian'
  with_items:
    - bash-completion
    - htop
    - rsync
    - tmux
    - nmap
    - netcat-openbsd
