- name: install php
  pacman: name=php-fpm state=present
  when: ansible_os_family == 'Archlinux'
- name: deploy php.ini
  copy:
    src: php.ini
    dest: /etc/php/php.ini
- name: systemctl enable php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: True
