- name: include Archlinux.yml
  include: Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  static: no
- name: include RedHat.yml
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no
- name: include Debian.yml
  include: Debian.yml
  when: ansible_os_family == 'Debian'
  static: no
