- name: install vim
  yum: name=vim state=present
  when: ansible_os_family == 'RedHat'
- name: deploy vimrc at ansible
  become: yes
  become_user: ansible
  copy:
    src: vimrc
    dest: ~/.vimrc
- name: deploy vimrc at root
  become: yes
  copy:
    src: vimrc
    dest: ~/.vimrc
